### ISSUE TITLE
注册百度OCR API后使用OCR翻译图片时报错（mac）

### ISSUE THREAD

**Issue by hli16-thu** [CopyTranslator/CopyTranslator#250]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

#### 须知

1. 反馈前请先查看官网的使用指南，查看使用指南能够解决您90%的疑惑。
2. 请先在Issue中搜索是否有相关issue，重复的issue会直接被关闭。
3. 确保您使用的是最新的稳定版，如果您使用的是旧版本的软件，issue也会直接被关闭，请先尝试最新版。
4. 所有不按照模板填写的issue，我们将不会处理。
5. 请尝试关闭软件后删除[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))重启软件，看看问题是否仍存在。

### 系统环境（请填写以下信息）

 - CopyTranslator版本：v9.0.2
 - 出现问题时的模式：专注模式
 - 操作系统：macOS Catalina  10.15.5
 - 安装路径: /Applications/copytranslator.app
 - 额外配置：无

### 如何复现这个问题

详细描述问题的现象：
注册了百度OCR API并输入后，使用mac自带的shift+command+4(+ctrl)功能截图到剪贴板或者生成图片文件后再复制到剪贴板、或者使用微信ctrl+command+A截图到剪贴板，都会报错，报错内容如下（为什么不能发图片啊啊啊啊）
**A JavaScript error occurred in the main process**
Uncaught Exception:
Error: EROFS: read-only file system, open 'temp.png'
    at Object.fs.openSync (fs.js:577:3)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Object.fs.writeFileSync (fs.js:1321:33)
    at Object.e.exports.writeImageSync (/Applications/copytranslator.app/Contents/Resources/app.asar/background.js:226:155573)
    at Object.recognize (/Applications/copytranslator.app/Contents/Resources/app.asar/background.js:226:198912)
    at Object.checkImage (/Applications/copytranslator.app/Contents/Resources/app.asar/background.js:226:206858)
    at e.exports.wr.on (/Applications/copytranslator.app/Contents/Resources/app.asar/background.js:226:207072)
    at r.eventListeners.(anonymous function).r.eventListeners.(anonymous function).forEach.e (/Applications/copytranslator.app/Contents/Resources/app.asar/background.js:142:240815)
    at Array.forEach (<anonymous>)
    at e.exports.emit (/Applications/copytranslator.app/Contents/Resources/app.asar/background.js:142:240801)

详细描述重现问题的步骤：

1. 打开copytranslator
2. 复制图片（上述两种方式）
4. 弹出报错

### 请回答以下问题

问题出现时，当时的CopyTranslator的设置是怎么样的？**请将[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))打包为压缩包并上传到此处。**
我打包了没有发现在哪里上传哇

已知软件可能在某些环境下与某些软件存在冲突，**请逐个退出其他非必要软件，测试问题是否仍然存在**。
无吧

**问题与特定阅读器有关吗？**还是在浏览器及其他的阅读器也不可以使用？**请多测试几个阅读器。**
无

问题与特定翻译引擎有关吗？**请务必测试其他翻译引擎是否有类似问题？**如果是不能翻译，是不是全部都不能用呢？
无关

问题与特定文档有关么？如果是特定句子或文件相关，**请务必附上文档文件**，并说明出问题的段落。
无

之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该问题的版本号

**Comment by hli16-thu** [comment]
补充报错界面以及百度API填入界面
<img width="424" alt="截屏2020-06-01 11 32 22" src="https://user-images.githubusercontent.com/66241984/83387223-f3886d80-a41e-11ea-9396-5c988168b959.png">
<img width="320" alt="WX20200601-113716@2x" src="https://user-images.githubusercontent.com/66241984/83387228-f5eac780-a41e-11ea-9775-4c53ed3a4d4f.png">

补充配置文件
[copytranslator.zip](https://github.com/CopyTranslator/CopyTranslator/files/4710025/copytranslator.zip)

**Comment by sdlyzhq** [comment]
请问新版本的下载链接从哪里找呢？
